package finco.framework.mvc.view.component;


import finco.framework.proxy.AuthFinCo;

import javax.swing.*;
import java.awt.*;
import java.util.UUID;

public class CaptchaDialog extends JDialog
{
    String captcha;
    AuthFinCo auth;

	public CaptchaDialog(Frame parent, AuthFinCo auth)
	{
		super(parent);
		this.captcha = UUID.randomUUID().toString().substring(0, 4);
		this.auth = auth;

		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parses  your Java file into its visual envirenment.
		//{{ INIT_CONTROLS
		setModal(true);
		getContentPane().setLayout(null);
		setSize(200,200);
		setVisible(false);
//		getContentPane().add(JScrollPane1);
//		JScrollPane1.setBounds(24,24,200,200);
//		JScrollPane1.getViewport().add(JTextField1);
        setTitle("Enter the text below");
		JTextField1.setBounds(30,50,145,30);
		JTextField1.setEditable(false);
		getContentPane().add(JTextField1);
		JTextField2.setBounds(30,100,145,30);
		getContentPane().add(JTextField2);
		JButton_OK.setText("OK");
		JButton_OK.setActionCommand("OK");
		getContentPane().add(JButton_OK);
		JButton_OK.setBounds(30,150,96,24);

		// generate the string for the monthly bill
		JTextField1.setText(this.captcha);
		JTextField2.setText("");
		//}}

		//{{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		JButton_OK.addActionListener(lSymAction);
		//}}
	}

	//{{DECLARE_CONTROLS
//	JScrollPane JScrollPane1 = new JScrollPane();
	JTextField JTextField1 = new JTextField();
	JTextField JTextField2 = new JTextField();
	JButton JButton_OK = new JButton();
	//}}


	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == JButton_OK)
				JButtonOK_actionPerformed(event);
		}
	}

	void JButtonOK_actionPerformed(java.awt.event.ActionEvent event)
	{
	    auth.valid = isValidated();
		dispose();
			 
	}

	public boolean isValidated() {
	    return captcha.equals(JTextField2.getText());
    }
}
